pull_request_rules:
  - name: Dispatch GitHub Actions
    conditions:
      - label = dispatch
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: d1-dispatch.yml
              inputs:
                pr_title: "{{ title }}"
                pr_head: "{{ head }}"
